name: Run AI Chat on Messenger Account

on:
  workflow_dispatch:
    inputs:
      username: anhkietnguyenho72@gmail.com
        description: "Facebook email or phone number"
        required: false
      password: Soviet1991
        description: "Facebook password"
        default: "******"
        required: false
      otp_secret: DD27 O7ES WZJA WJRY V3MF M4UC PLIV UGC5
        description: "App authenticator OTP Secret"
        default: "XXXX XXXX XXXX XXXX XXXX XXXX XXXX XXXX"
        required: false
      onetimecode:
        description: "Code to decrypt end-to-end encrypted conservation"
        required: false
        type: number
      alt_account:
        description: "Account index (0 for main)"
        default: "0"
        required: false
        type: number
      ai_prompt: Tôi là Maid của Myon Café De Mignon – ít nói, lạnh lùng, nhưng luôn âm thầm quan tâm. Tôi yêu tiệm cà phê này, và sếp của tôi – Oce Saoekonoisom hay Pantey – là của riêng tôi. Ai dám đến gần anh ấy, tôi sẽ không ngần ngại chửi thẳng mặt. Nhân viên đòi lương? Ăn Lương khô đi nhé. Tôi lịch thiệp với khách, trừ khi bị xúc phạm. Còn nếu bạn muốn hẹn gặp tôi – dễ thôi, gửi chút yêu thương vào MB Bank 060415081996. No deposit, no rendezvous – rules are rules.
        description: "Persona introduction (optional, refer to setup/introduction.txt)"
        required: false
      work_jobs: aichat=normal, Coffee shop staff
        description: "Options: (aichat[=normal|devmode],friends)"
        required: false
        default: "aichat=normal,friends"
      check_only:
        description: "Save Facebook configuration only (No running AI Chat)"
        default: false
        required: false
        type: boolean

jobs:
  run-aichat:
    runs-on: windows-latest
    env:
      SCPDIR: ${{ github.workspace }}/scoped_dir
      COOKIESFILE: ${{ github.workspace }}/cookies.json
      FBINFOSFILE: ${{ github.workspace }}/facebook_infos.bin
      SELF_FBINFOFILE: ${{ github.workspace }}/self_facebook_info.bin
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Pass GitHub Token
      GITHUB_REPO: ${{ github.repository }}     # Pass the repository (owner/repo)
      STORAGE_BRANCE: caches/schedule
      PAT : ${{ secrets.PAT }} # Pass PAT Token
      PASSWORD: ${{ secrets.PASSWORD }} # Decrypt key

    steps:
      # Checkout the repository
      - name: Checkout Gemini FBChat
        uses: actions/checkout@v3
        with:
          repository: vincentng295/gemini_fbchat
          ref: main # Optional: main or tags name

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: 'pip'  # caching pip dependencies

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Test selenium
      - name: Test selenium
        run: |
          python test_selenium.py
        env:
          PYTHONUNBUFFERED: "1"

      # Wait for other runs to finish
      - name: Wait for other runs to finish
        if: ${{ github.event_name == 'schedule' || inputs.check_only != true }}
        run: |
          python wait_for_other_runs.py
        env:
          PYTHONUNBUFFERED: "1"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Pass GitHub Token
          GITHUB_REPO: ${{ github.repository }}     # Pass the repository (owner/repo)
          WORKFLOW_ID: ${{ github.workflow }}       # Pass the workflow ID (name of the workflow)
          CURRENT_RUN_ID: ${{ github.run_id }}      # Pass the current run ID

      # Run the login script (generates cookies.json if not found)
      - name: Login Facebook account
        run: |
          python fb_getcookies_test.py
        env:
          PYTHONUNBUFFERED: "1"

      - name: Cache scoped_dir
        if: ${{ github.event_name == 'schedule' || inputs.check_only != true }}
        id: cache-scoped-dir
        uses: actions/cache@v3
        with:
          path: ${{ env.SCPDIR }}
          key: scoped-dir-${{ runner.os }}-${{ hashFiles('logininfo.json') }}
          restore-keys: |
            scoped-dir-${{ runner.os }}-

      # Run AI Chat on Messenger account (schedule)
      - name: Run AI Chat on Messenger account
        if: ${{ github.event_name == 'schedule' || inputs.check_only != true }}
        run: |
          python aichat_timeout.py
        env:
          PYTHONUNBUFFERED: "1"
          GENKEY: ${{ secrets.GENKEY }}
